verbose = true
max_width = 100
error_on_line_overflow = true
tab_spaces = 4
fn_call_width = 80
struct_lit_width = 18
struct_variant_width = 35
force_explicit_abi = true
fn_brace_style = "SameLineWhere"
item_brace_style = "SameLineWhere"
control_style = "Rfc"
control_brace_style = "AlwaysSameLine"
impl_empty_single_line = true
trailing_comma = "Vertical"
fn_empty_single_line = true
fn_single_line = false
fn_return_indent = "WithArgs"
where_style = "Rfc"
generics_indent = "Block"
struct_lit_style = "Block"
struct_lit_multiline_style = "PreferSingle"
fn_call_style = "Block"
report_todo = "Never"
report_fixme = "Never"
chain_indent = "Block"
chain_one_line_max = 35
chain_split_single_child = false
reorder_imports = true
reorder_imports_in_group = true
reorder_imported_names = true
take_source_hints = true
wrap_comments = true
comment_width = 100
normalize_comments = false
wrap_match_arms = false
match_arm_blocks = false
match_block_trailing_comma = true
indent_match_arms = true
closure_block_indent_threshold = 1
use_try_shorthand = true
write_mode = "Diff"
condense_wildcard_suffixes = true

[width_heuristics]
chain_width = 40
fn_call_width = 80
struct_lit_width = 35
struct_variant_width = 35
array_width = 80
single_line_if_else_max_width = 60
